# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oasdiff < Formula
  desc ""
  homepage "https://github.com/tufin/oasdiff"
  version "1.3.18"

  on_macos do
    url "https://github.com/Tufin/oasdiff/releases/download/v1.3.18/oasdiff_1.3.18_darwin_all.tar.gz"
    sha256 "ce007a37360f63125100eb6571939693712a04c0640ffaa5133dc83f063b2089"

    def install
      bin.install "oasdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Tufin/oasdiff/releases/download/v1.3.18/oasdiff_1.3.18_linux_amd64.tar.gz"
      sha256 "af7476912b52997613d67957b79f105d972b76497abc5fc599e6c8101078b7f9"

      def install
        bin.install "oasdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tufin/oasdiff/releases/download/v1.3.18/oasdiff_1.3.18_linux_arm64.tar.gz"
      sha256 "edbc848a753c2282fba3375b42d8361269f120d8569fc30ec6da9e8f32f86a0a"

      def install
        bin.install "oasdiff"
      end
    end
  end
end
