# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oasdiff < Formula
  desc ""
  homepage "https://github.com/tufin/oasdiff"
  version "1.1.29"

  on_macos do
    url "https://github.com/Tufin/oasdiff/releases/download/v1.1.29/oasdiff_1.1.29_darwin_all.tar.gz"
    sha256 "c4d3b9d84c05fa536e746e9c1696314cfb33b1ef39109b6c6a6c9a6c12d39c54"

    def install
      bin.install "oasdiff"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tufin/oasdiff/releases/download/v1.1.29/oasdiff_1.1.29_linux_arm64.tar.gz"
      sha256 "14642d0ca28343566291d2cf6e35e9c6afe5a67ecdb9c589c5edb01a8ebdd876"

      def install
        bin.install "oasdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tufin/oasdiff/releases/download/v1.1.29/oasdiff_1.1.29_linux_amd64.tar.gz"
      sha256 "a19e2fdd257e75e1a8dd424c10b8ad60cc1a7a67f05ec7ad3309eca21956f61e"

      def install
        bin.install "oasdiff"
      end
    end
  end
end
